project:
  type: website

website:
  title: "Portfolio"
  favicon: "profile.jpg"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/andypicke/
      - icon: linkedin
        href: https://www.linkedin.com/in/andypicke/
  search: 
    location: navbar
    type: overlay
format:
  html:
    theme: cosmo
    css: styles.css
    code-link: true
    code-fold: show
    code-tools: true
    highlight-style: github
editor: visual

