project:
  type: website

website:
  title: "Portfolio"
  favicon: "profile2.jpg"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd
      - text: Resume
        href: resume.qmd
      - text: Resources
        href: resources.qmd
      - text: Publications
        href: publications.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/andypicke/
      - icon: linkedin
        href: https://www.linkedin.com/in/andypicke/
      - icon: twitter
        href: https://twitter.com/andypicke
  search: 
    location: navbar
    type: overlay
format:
  html:
    theme: cosmo
    css: styles.css
    code-link: true
    code-fold: show
    code-tools: true
    highlight-style: github
editor: visual
execute:
  freeze: auto  # re-render only when source changes