---
title: "Data Science Resources"
about:
  template: trestles
  links: 
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/andypicke/
    - icon: github
      text: Github
      href: https://github.com/andypicke
    - icon: envelope
      text: Contact Me
      href: mailto:andypicke@gmail.com
    - icon: twitter
      text: Twitter
      href: twitter.com/andypicke
---

Here are some resources and data sources that I have found interesting or useful:

# Software

## R

-   [R-bloggers](https://www.r-bloggers.com/)

## Python

## Quarto

-   <https://quarto.org/>

-   [Tutorial on Creating a Data Science Portfolio with Quarto](https://www.youtube.com/watch?v=xtSFXtDf4cM)

-   [Markdown basics](https://quarto.org/docs/authoring/markdown-basics.html)

# Data

## Weather/Environment

-   [CoAgMet](https://coagmet.colostate.edu/)

    -   <https://github.com/andypicke/rcoagmet>
    -   <https://andypicke.quarto.pub/portfolio/posts/rcoagmet/rcoagmet.html>

-   <https://doi-usgs.github.io/dataRetrieval/>

-   <https://bluegreen-labs.github.io/snotelr/>

## Energy

-   [Alternative Fuels Data Center](https://afdc.energy.gov/)

-   [U.S. Energy Information Administration (EIA)](https://www.eia.gov/opendata/)

    -   <https://github.com/ropensci/eia>

-   [Our World in Data](https://ourworldindata.org/energy)

-   [Ember](https://ember-climate.org/data/) is "an independent energy think tank that aims to accelerate the clean energy transition with data and policy". Data is available to download or through an API.

    -   <https://github.com/andypicke/emberr>
    -   <https://andypicke.quarto.pub/portfolio/posts/emberr/emberr.html>

-   [GridStatus](https://www.gridstatus.io/home) provides data on the US electric grid from various sources. You can explore the data on their website, and they also have a API.

    -   <https://github.com/andypicke/rgridstatus>
    -   <https://andypicke.quarto.pub/portfolio/posts/rGridStatus/rGridStatus.html>

-   <https://globalenergymonitor.org/>

-   <https://eerscmap.usgs.gov/uspvdb/>

    -   <https://andypicke.quarto.pub/portfolio/posts/USPVDB/USPVDB_Analysis.html>

-   <https://eerscmap.usgs.gov/uswtdb/>

# Other

-   [Data Is Plural](https://www.data-is-plural.com/)
-   [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday)

# Miscellaneous

-   A guide to standard [HTTP Status Codes](https://restfulapi.net/http-status-codes/) that may be returned when requesting data from an API.
